version: 0.0

Resources:
  - JavaWebApp:                       
      Type: KubernetesResource
      Properties:
        Files:
          - deployment/deployment.yaml
          - deployment/service.yaml   
