version: 0.2

env:
  variables:
    IMAGE_REPO: "418295691381.dkr.ecr.us-east-1.amazonaws.com/cinema"
    CLUSTER_NAME: "cluster1"
    K8S_NAMESPACE: "default"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Compiling Java sources..."
      - mkdir -p build/classes
      - find src -name '*.java' | xargs javac -d build/classes
      - echo "Packaging into JAR..."
      - jar cvf build/app.jar -C build/classes .
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR…"
      - aws --version
      - aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $IMAGE_REPO
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Will build & push image tag $IMAGE_REPO:$IMAGE_TAG"
  build:
    commands:
      - echo "Building Docker image…"
      - docker build -t $IMAGE_REPO:$IMAGE_TAG .
      - docker push $IMAGE_REPO:$IMAGE_TAG
  post_build:
    commands:
      - echo "Deploying to EKS…"
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $AWS_REGION
      - kubectl set image deployment/java-webapp \
          java-webapp=$IMAGE_REPO:$IMAGE_TAG \
          --namespace $K8S_NAMESPACE
      - kubectl rollout status deployment/java-webapp \
          --namespace $K8S_NAMESPACE

artifacts:
  files: none
