apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_HOST: Y2luZW1hLWRiLWluc3RhbmNlLmNycXdnOHlzNjN3dC51cy1lYXN0LTEucmRzLmFtYXpvbmF3cy5jbw== # This is the NEW, CORRECT endpoint
  DB_NAME: cG9zdGdyZXM= # postgres
  DB_PASSWORD: bWRvbmx5MTIz # mdonly123
  DB_PORT: NTQzMg== # 5432
  DB_USER: cG9zdGdyZXM= # postgres
